CREATE TABLE dbo.ADDRESS (
	ADDRESS_ID			INT IDENTITY(1, 1)	NOT NULL,
	HOUSE_NAME			VARCHAR(50)			NULL,
	STREET				VARCHAR(50)			NULL,
	TOWN				VARCHAR(50)			NULL,
	CITY				VARCHAR(50)			NULL,
	POSTCODE			VARCHAR(10)			NULL
)
GO

CREATE TABLE dbo.SETTINGS (
	SETTINGS_ID			INT IDENTITY(1, 1)	NOT NULL,
	CONTACT_EMAIL		VARCHAR(200)		NOT NULL,
	CONTACT_NUMBER		VARCHAR(30)			NOT NULL,
	CONTACT_ADDRESS_ID	INT					NOT NULL
)
GO

CREATE TABLE dbo.USER_ACCOUNT (
	USER_ACCOUNT_ID		INT IDENTITY(1,1)	NOT NULL,
	USERNAME			VARCHAR(50)			NOT NULL,
	PASSWORD_HASH		VARCHAR(MAX)		NOT NULL,
	PASSWORD_SALT		VARCHAR(MAX)		NOT NULL
)
GO
