ALTER TABLE ADDRESS
ADD CONSTRAINT PK_ADDRESS PRIMARY KEY CLUSTERED (ADDRESS_ID)
GO

ALTER TABLE SETTINGS
ADD CONSTRAINT PK_SETTINGS PRIMARY KEY CLUSTERED (SETTINGS_ID)
GO

ALTER TABLE USER_ACCOUNT
ADD CONSTRAINT PK_USER_ACCOUNT PRIMARY KEY CLUSTERED (USER_ACCOUNT_ID)
GO 