ALTER TABLE PRICE_POINT
ADD CONSTRAINT FK_PRICE_POINT_PRICE FOREIGN KEY (PRICE_ID)
REFERENCES PRICE(PRICE_ID)
GO

ALTER TABLE SETTINGS
ADD CONSTRAINT FK_SETTINGS_ADDRESS FOREIGN KEY (CONTACT_ADDRESS_ID)
REFERENCES ADDRESS(ADDRESS_ID)
GO